Consider the below code to answer further questions:

import numpy as np<br>
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ] <br>
array_list = np.array(object = list_)

Q1 . Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

Answer: 
Yes, there is a difference in the data type of variables list_ and array_list.

The variable list_ is a python list while array_list is a numpy array.

To print the data types of both variables, we can use the type() function. 

In [1]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


Q2. Write a code to print the data type of each and every element of both the variables list_ and
array_list.

In [3]:
# For list_
for i in range(len(list_)):
    print(f"{type(list_[i])}")

# For array_list
for row in array_list:
    for elem in row:
        print(f"{type(elem)}")

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and array_list.

Answer: <br> Yes, there will be a difference in the data type of the elements present in both the variables, list_ and arra_list. The elements in the list_ will have their original data type whereas the elements in arra_list will have a data type of 'int'.

In [7]:
import numpy as np

list_ = ['1','2','3','4','5']
array_list = np.array(object = list_ ,dtype=int)

for element in list_:
    print(type(element))

for element in array_list:
    print(type(element))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


Consider the below code to answer further questions:

import numpy as np<br>
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]<br>
num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array: <br>
(i) shape <br>
(ii) size

In [8]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

shape = np.shape(num_array)
size = np.size(num_array)

print("Shape of num_array:", shape)
print("Size of num_array:", size)

Shape of num_array: (2, 3)
Size of num_array: 6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [9]:
import numpy as np

my_array = np.zeros((3,3))
print(my_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [10]:
import numpy as np

identity_matrix = np.identity(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
